import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {allowedOrigin,normalizeProfile,readClaims} from '../functions/codevalanche-account/validation.mjs';
const userId='11111111-1111-4111-8111-111111111111', sessionId='22222222-2222-4222-8222-222222222222';
let user={id:userId,email:'test@example.test',email_confirmed_at:'2026-09-08',user_metadata:{codevalanche_admin:true},app_metadata:{},identities:[]};
let active=true,blocked=false,invalid=false,writes=[];
const db={auth:{getUser:async()=>({data:{user:invalid?null:user},error:invalid?new Error():null}),admin:{}},rpc:async(name)=>({data:name==='codevalanche_sessions'?(active?[{id:sessionId}]:[]):true,error:null}),from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{blocked},error:null}),upsert:async(data)=>{writes.push(data);return {data:null,error:null}}})};
let handler;
const source=await readFile(new URL('../functions/codevalanche-account/index.ts',import.meta.url),'utf8');
const runnable=stripTypeScriptTypes(source.replace(/^import .*;\r?\n/gm,''));
new Function('createClient','Deno','allowedOrigin','normalizeProfile','readClaims',runnable)(()=>db,{env:{get:()=> 'test'},serve:fn=>{handler=fn}},allowedOrigin,normalizeProfile,readClaims);
const jwt=`e30.${Buffer.from(JSON.stringify({sub:userId,session_id:sessionId})).toString('base64url')}.signature`;
const request=(action,extras={})=>new Request('https://example.test',{method:'POST',headers:{authorization:`Bearer ${jwt}`,'content-type':'application/json',origin:'https://codevalanche.com'},body:JSON.stringify({action,...extras})});
test('get-account returns only the verified subject and session',async()=>{const r=await handler(request('get-account'));const body=await r.json();assert.equal(r.status,200);assert.equal(body.userId,userId);assert.equal(body.session_id,sessionId);assert.equal(body.sessions[0].current,true)});
test('revoked JWT is denied despite getUser accepting it',async()=>{active=false;try{assert.equal((await handler(request('get-account'))).status,401)}finally{active=true}});
test('blocked account is denied with still valid session',async()=>{blocked=true;try{assert.equal((await handler(request('get-account'))).status,403)}finally{blocked=false}});
test('user-editable metadata cannot grant administrator access',async()=>{assert.equal((await handler(request('admin-list-users'))).status,403)});
test('cannot revoke another user session',async()=>{writes=[];assert.equal((await handler(request('revoke-session',{sessionId:'33333333-3333-4333-8333-333333333333'}))).status,404);assert.equal(writes.length,0)});
test('deletion needs explicit confirmation',async()=>{writes=[];assert.equal((await handler(request('request-deletion'))).status,400);assert.equal(writes.length,0)});
test('invalid authentication never reaches account response',async()=>{invalid=true;try{assert.equal((await handler(request('get-account'))).status,401)}finally{invalid=false}});
test('oversized request rejected',async()=>{assert.equal((await handler(request('get-account',{junk:'x'.repeat(17000)}))).status,413)});

test('sign-out-current uses provider local revocation',async()=>{let scope;db.auth.admin.signOut=async(token,value)=>{scope=value;return {error:null}};assert.equal((await handler(request('sign-out-current'))).status,200);assert.equal(scope,'local')});
